language: swift
xcode_project: BodyBuilder.xcodeproj # path to your xcodeproj folder
xcode_scheme: BodyBuilder
osx_image: xcode8.3

script: 
- xcodebuild -scheme BodyBuilder -project BodyBuilder.xcodeproj -destination 'platform=OS X' build test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'BodyBuilder'
  
