language: swift
xcode_project: BodyBuilder.xcodeproj # path to your xcodeproj folder
xcode_scheme: BodyBuilder

script: 
- xcodebuild -scheme BodyBuilder -project BodyBuilder.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator, id=75FC400A-B2AA-4DD6-B159-8687FAA5018A, OS=9.3, name=iPhone 4s' build test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'BodyBuilder'
  
